---
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'monitoring'

scrape_configs:

  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']


  - job_name: "minio"
    scrape_interval: 5s
    metrics_path: '/minio/v2/metrics/cluster'
    static_configs:
      - targets:
          - "minio:9000"
        labels:
          env: "monitoring"

  - job_name: 'nodeexporter-monitoring'
    scrape_interval: 5s
    static_configs:
      - targets: ['nodeexporter:9100']

  - job_name: 'cadvisor-monitoring'
    scrape_interval: 5s
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'missing-container-metrics-monitoring'
    scrape_interval: 5s
    static_configs:
      - targets: ['missing-container-metrics:3001']
